// <auto-generated />
using System;
using Ibvc.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ibvc.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Ibvc.Domain.Entities.Batismo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Igreja")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pastor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Batismo");
                });

            modelBuilder.Entity("Ibvc.Domain.Entities.ProfissaoDeFe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Igreja")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pastor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProfissaoDeFe");
                });

            modelBuilder.Entity("Ibvc.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BatismoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Celular")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Complemento")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConjugeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataCasamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EstadoCivil")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Genero")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeioAdmissao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Naturalidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeConjuge")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeMae")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePai")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProfissaoDeFeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BatismoId");

                    b.HasIndex("ConjugeId")
                        .IsUnique();

                    b.HasIndex("ProfissaoDeFeId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Ibvc.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Ibvc.Domain.Entities.Batismo", "Batismo")
                        .WithMany()
                        .HasForeignKey("BatismoId");

                    b.HasOne("Ibvc.Domain.Entities.Usuario", "Conjuge")
                        .WithOne()
                        .HasForeignKey("Ibvc.Domain.Entities.Usuario", "ConjugeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ibvc.Domain.Entities.ProfissaoDeFe", "ProfissaoDeFe")
                        .WithMany()
                        .HasForeignKey("ProfissaoDeFeId");

                    b.Navigation("Batismo");

                    b.Navigation("Conjuge");

                    b.Navigation("ProfissaoDeFe");
                });
#pragma warning restore 612, 618
        }
    }
}
